os: linux

language: c

before_install:
  - test -n $CC && unset CC
  - eval "${MATRIX_EVAL}"

install: make get-deps

compiler: gcc 

script:
  - make
  - make run_tests

notifications:
  email: false