os: linux

language: c

before_install:
  - test -n $CC && unset CC
  - eval "${MATRIX_EVAL}"

compiler: gcc 

before script: echo "Crash and Hang Tests"

script:
  - make

notifications:
  email: false